version: 1

policy:
  pullRequests: public

tasks:

  $let:
    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else: ${event.after}

    clone_url:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.git_url}}
      else: ${event.repository.url}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}

  in:
    $if: 'tasks_for in ["github-pull-request", "github-push"]'
    then:
      - taskId: {$eval: as_slugid("One-off System Add-ons Lint Tests")}
        created: {$fromNow: ''}
        deadline: {$fromNow: '1 hour'}
        provisionerId: proj-misc
        workerType: ci
        payload:
          maxRunTime: 1200
          image: "standard8/one-off-system-add-ons:2017081801.a6a1f5c1d971"
          command:
          - "/bin/bash"
          - "-lc"
          - "git clone ${clone_url} repo && cd repo && git checkout ${head_rev} && npm install && npm run lint"
        metadata:
          name: One-off System Add-ons Lint Tests
          description: One-off System Add-ons Lint Tests
          owner: taskcluster-internal@mozilla.com
          source: ${repository}
